name: Staging deployment

on:
  push:
    branches: [main]

jobs: 
  build:
   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files    
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - shell: bash
        env:
         SUPER_SECRET: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $SUPER_SECRET
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: saiseyon
          password: 4f6c3e7a-0dab-4c93-8fcd-b0358278b6bb
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: saiseyon/dev-repo:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout files    
        uses: actions/checkout@v2
      
      - name: Get tag name
        uses: olegtarasov/get-tag@v2
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: 62cb741ebf588510e6c561389de389529e28f484325a250de2fc83d8af83d4e2         
      - name: Provision Droplet and deploy container
        run: doctl compute droplet create doctldockerdemo --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait
